ProjectManager/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjectManager.PL.ViewModels
{
    public class ProjectViewModel
    {
        public ICollection<ProjectTaskViewModel> TasksViewModels { get; set; }
        public Guid Id { get; set; }
        public string Title { get; set; }

        [Display(Name = "Customer Company")] 
        public string CustomerCompany { get; set; }

        [Display(Name = "Performer Company")] 
        public string PerformerCompany { get; set; }

        [Display(Name = "Start Date")] 
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")] 
        public DateTime EndDate { get; set; }

        public uint Priority { get; set; }
        public ICollection<ProjectTaskViewModel> Tasks { get; set; }
        public EmployeeViewModel Manager { get; set; }
        public Guid ManagerId { get; set; }
    }
}

ProjectManager/Controllers/EmployeesController.cs
using System;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectManager.BLL.Models;
using ProjectManager.BLL.Services;
using ProjectManager.PL.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ProjectManager.PL.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        public EmployeesController(IEmployeeService employeeManager,
            IMapper mapper)
        {
            EmployeeManager = employeeManager;
            Mapper = mapper;
        }

        private IEmployeeService EmployeeManager { get; }
        private IMapper Mapper { get; }

        public async Task<IActionResult> Index()
        {
            var employees = await EmployeeManager.GetAllAsync(User);
            return View(Mapper.Map<ICollection<EmployeeViewModel>>(employees));
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var employee = await EmployeeManager.GetAsync(User, id);

            if (employee == null) 
                return NotFound();

            return View(Mapper.Map<EmployeeViewModel>(employee));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                await EmployeeManager.CreateAsync(User, Mapper.Map<EmployeeModel>(employee));
                return RedirectToAction(nameof(Index));
            }

            return View(employee);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var employee = await EmployeeManager.GetAsync(User, id);

            if (employee == null) 
                return NotFound();

            return View(Mapper.Map<EmployeeViewModel>(employee));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await EmployeeManager.EditAsync(User, Mapper.Map<EmployeeModel>(employee));
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(employee);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var employee = await EmployeeManager.GetAsync(User, id);

            if (employee == null) 
                return NotFound();

            return View(Mapper.Map<EmployeeViewModel>(employee));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(Guid id)
        {
            await EmployeeManager.RemoveByIdAsync(User, id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjectManager/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.BLL.Models;
using ProjectManager.BLL.Services;
using ProjectManager.PL.ViewModels;

namespace ProjectManager.PL.Controllers
{
    [Authorize]
    [Route("projects")]
    public class ProjectsController : Controller
    {
        public ProjectsController(
            IProjectService projectManager,
            IMapper mapper
        )
        {
            ProjectService = projectManager ?? throw new ArgumentNullException(nameof(projectManager));
            Mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        private IProjectService ProjectService { get; }
        private IMapper Mapper { get; }

        [HttpGet("index")]
        public async Task<IActionResult> Index()
        {
            var projects = await ProjectService.GetAllAsync(User);

            return View(Mapper.Map<IEnumerable<ProjectViewModel>>(projects));
        }

        [HttpGet("details")]
        public async Task<IActionResult> Details(Guid id)
        {
            var project = await ProjectService.GetAsync(User, id);

            if (project == null) 
                return NotFound();

            return View(Mapper.Map<ProjectViewModel>(project));
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            var data = new ProjectViewModel();
            return View(data);
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(ProjectViewModel project)
        {
            if (ModelState.IsValid)
            {
                await ProjectService.CreateAsync(User, Mapper.Map<ProjectModel>(project));

                return RedirectToAction("Index", new {project.Id});
            }

            return View(project);
        }

        [HttpGet("{id}/update")]
        public async Task<IActionResult> Update(Guid id)
        {
            var project = await ProjectService.GetAsync(User, id);
            return View(Mapper.Map<ProjectViewModel>(project));
        }

        [HttpPost("{id}/update")]
        public async Task<IActionResult> Update(ProjectViewModel project)
        {
            if (ModelState.IsValid)
            {
                await ProjectService.EditAsync(User, Mapper.Map<ProjectModel>(project));

                return RedirectToAction("Index", new {project.Id});
            }

            return View(project);
        }
    }
}

ProjectManager/Controllers/SharedController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.PL.ViewModels;

namespace ProjectManager.PL.Controllers
{
    public class SharedController : Controller
    {
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Shared/Error",
                new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

ProjectManager/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.BLL.Models;
using ProjectManager.BLL.Services;
using ProjectManager.PL.ViewModels;

namespace ProjectManager.PL.Controllers
{
    public class TasksController : Controller
    {
        public TasksController(ITaskService taskService,
            IMapper mapper)
        {
            TaskService = taskService;
            Mapper = mapper;
        }

        private ITaskService TaskService { get; }
        private IMapper Mapper { get; }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {
            var tasks = await TaskService.GetAllAsync(User);
            return View(Mapper.Map<IEnumerable<ProjectTaskViewModel>>(tasks));
        }

        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var task = await TaskService.GetAsync(User, id);

            if (task == null) 
                return NotFound();

            return View(Mapper.Map<ProjectTaskViewModel>(task));
        }

        // GET: Tasks/Create
        public IActionResult Create()
        {
            var task = new ProjectTaskViewModel();
            return View(task);
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectTaskViewModel task)
        {
            if (ModelState.IsValid)
            {
                await TaskService.CreateAsync(User, Mapper.Map<ProjectTaskModel>(task));
                return RedirectToAction("Index", new {task.Id});
            }

            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var task = await TaskService.GetAsync(User, id);
            return View(Mapper.Map<ProjectTaskViewModel>(task));
        }

        // POST: Tasks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectTaskViewModel task)
        {
            if (ModelState.IsValid)
            {
                await TaskService.EditAsync(User, Mapper.Map<ProjectTaskModel>(task));

                return RedirectToAction("Index", new {task.Id});
            }

            return View(task);
        }
    }
}

ProjectManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/flick/jquery-ui.css" type="text/css" />
    <link rel="stylesheet" href="https://unpkg.com/vue-form-wizard/dist/vue-form-wizard.min.css" />
    <link rel="stylesheet" href="~/lib/vue2-datepicker/index.css" type="text/css" />
</head>
<body>
    <header class="sticky-top">
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <div class="container">
                <button class="navbar-toggler pb-0 pt-0 pl-1 pr-1" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" asp-route-taskGroupId="">Project Manager</a>

                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_NavPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>temicch &copy; Project Manager 2020</span>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/jqueryui-touch-punch/jquery.ui.touch-punch.min.js"></script>
    <script src="~/js/swipeable.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-form-wizard/dist/vue-form-wizard.js"></script>
    <script src="~/lib/vue2-datepicker/index.js"></script>    
    
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", false)
</body>
</html>

<script>
    // Automatic scrolling to inputs that are selected, makes mobile entry smoother
    document.addEventListener("DOMContentLoaded",
        function() {
            $("input").focus(() => smoothSlide(document.activeElement));
            $("textarea").focus(() => smoothSlide(document.activeElement));
            $(".collapse").on("show.bs.collapse", (e) => smoothSlide(e.currentTarget));
        });

    function smoothSlide(element) {
        window.setTimeout(() => element.scrollIntoView({ block: "center", behavior: 'smooth' }), 400);
    }
</script>

ProjectManager/Views/Shared/_NavPartial.cshtml
@using ProjectManager.BLL
@if (User.Identity.IsAuthenticated)
{
    <a class="nav-link text-dark" id="tasks-Dropdown" role="button" asp-area="" asp-controller="Projects" asp-action="Index">
        Projects
    </a>
    @*<div class="dropdown-menu" aria-labelledby="tasks-Dropdown">
        @await Component.InvokeAsync("TaskGroupList")
    </div>*@
    @if (User.IsInRole(Roles.Leader))
    {
        <a class="nav-link text-dark" id="tasks-Dropdown" role="button" asp-area="" asp-controller="Employees" asp-action="Index">
            Employees
        </a>
    }
}

ProjectManager/Views/Shared/_NothingToShow.cshtml
<p class="lead col-md-offset-3">There is no entities avaiable for you.</p>

ProjectManager/Views/Shared/_Projects.cshtml
@model IEnumerable<ProjectManager.PL.ViewModels.ProjectViewModel>

<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h3 class="flex-grow-1 flex-shrink-1 text-truncate">Projects</h3>
    @*<div class="flex-shrink-0 flex-grow-0 mb-2">
        <a asp-action="Create" asp-controller="Projects" class="btn btn-success btn-icon-split ">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text">Add</span>
        </a>
    </div>*@
</div>

<div class="table-responsive">
    @if (Model != null && Model.Count() > 0)
    {
        <table class="table">
            <thead>
            <tr>
                <th class="text-center">@Html.DisplayNameFor(x => x.Title)</th>
                <th class="text-center">@Html.DisplayNameFor(x => x.Manager)</th>
                <th class="text-center">Customer</th>
                <th class="text-center">Performer</th>
                <th class="text-center">@Html.DisplayNameFor(x => x.StartDate)</th>
                <th class="text-center">@Html.DisplayNameFor(x => x.EndDate)</th>
                <th class="text-center">@Html.DisplayNameFor(x => x.Priority)</th>
                <th class="text-center">Tasks</th>
            </tr>
            </thead>
            <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@item.Title</td>
                    <td class="text-center">
                        <a asp-action='Details' asp-controller='Employees' asp-route-id='@(item?.Manager?.Id)'>
                            @(item?.Manager?.SimplifiedName ?? "")
                        </a>
                    </td>
                    <td class="text-center">@item.CustomerCompany</td>
                    <td class="text-center">@item.PerformerCompany</td>
                    <td class="text-center">@item.StartDate.ToString("dd.MM.yyyy")</td>
                    <td class="text-center">@item.EndDate.ToString("dd.MM.yyyy")</td>
                    <td class="text-center">@item.Priority</td>
                    <td class="text-center">@item?.Tasks?.Count</td>
                    <td class="text-center">
                        <div class="btn-group">
                            <a class="btn btn-info btn-just-icon btn-sm m-1" title="Info" asp-action="Details" asp-route-id="@item.Id">
                                <i class="fas fa-info-circle"></i>
                            </a>
                            @*<a class="btn btn-success btn-just-icon btn-sm m-1" title="Edit" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a class="btn btn-danger btn-just-icon btn-sm m-1" title="Remove" asp-action="Delete" asp-route-id="@item.Id">
                                    <i class="fa fa-times"></i>
                                </a>*@
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <partial name="_NothingToShow"/>
    }
</div>

ProjectManager/Views/Shared/_Tasks.cshtml
@model IEnumerable<ProjectManager.PL.ViewModels.ProjectTaskViewModel>

<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h3 class="flex-grow-1 flex-shrink-1 text-truncate">Tasks</h3>
    @*<div class="flex-shrink-0 flex-grow-0 mb-2">
        <a asp-action="Create" asp-controller="Tasks" class="btn btn-success btn-icon-split ">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text">Add</span>
        </a>
    </div>*@
</div>

<div class="table-responsive">
    @if (Model != null && Model.Count() > 0)
    {
        <table class="table">
            <thead>
            <tr>
                <th class="text-center">#</th>
                <th>@Html.DisplayNameFor(x => x.Author)</th>
                <th>@Html.DisplayNameFor(x => x.Title)</th>
                <th>@Html.DisplayNameFor(x => x.Performer)</th>
                <th>@Html.DisplayNameFor(x => x.Comment)</th>
                <th>@Html.DisplayNameFor(x => x.Priority)</th>
                <th>@Html.DisplayNameFor(x => x.Status)</th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@item.Id</td>
                    <td>@(item?.Author?.SimplifiedName ?? string.Empty)</td>
                    <td>@item.Title</td>
                    <td>@(item?.Performer?.SimplifiedName ?? string.Empty)</td>
                    <td>@item.Comment</td>
                    <td>@item.Priority</td>
                    <td>@item.Status</td>
                    <td class="td-actions">
                        <div class="btn-group">
                            <a class="btn btn-info btn-just-icon btn-sm m-1" title="Info" asp-controller="Tasks" asp-action="Details" asp-route-id="@item.Id">
                                <i class="fas fa-user"></i>
                            </a>
                            @*<a class="btn btn-success btn-just-icon btn-sm m-1" title="Edit" asp-controller="Tasks" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a class="btn btn-danger btn-just-icon btn-sm m-1" title="Remove" asp-controller="Tasks" asp-action="Delete" asp-route-id="@item.Id">
                                    <i class="fa fa-times"></i>
                                </a>*@
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <partial name="_NothingToShow"/>
    }
</div>